### ISSUE TITLE
why are all nodes ID the same in k-bucket?

### ISSUE THREAD

**Issue by nonam3e** [f0lg0/kademlia-dht#4]
![image](https://user-images.githubusercontent.com/71525212/145716147-87b69ff3-e63f-44dc-bcbb-a00f7de17d84.png)

**Comment by f0lg0** [comment]
From a first look the error should be here where instead of using `n.id` I use `interface.node.id` but I'm not sure yet...
```
for kb in flattened {
        for n in &kb.nodes {
            let kbucket = serde_json::json!({
                "nodes": {
                    "ip": n.ip,
                    "port": n.port,
                    "id": format!("{:?}", interface.node.id),
                },
                "size": kb.size,
            });
            parsed_buckets.push(kbucket);
        }
    }
```
Will try a fix as soon as I can, thanks for pointing this out.

**Comment by f0lg0** [comment]
> 

solved it, thanks for pointing this out
![img](https://github.com/f0lg0/kademlia-dht/blob/main/images/dump.png?raw=true)
